### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by reddo136** [abc123me/Nividia-Fancontrol#7]
Hi, thank you for your effort in this project.
I'm using this with a gigabyte 1060 that is set by default to go fanless till 60°C.

I'm experiencing a high cpu load with this script, as "top" displays 8% cpu on main.py. Is this normal? Works fine however as video card remains in the 30-35°C range while idle.

Thank you,
Gio

**Comment by abc123me** [comment]
I was unable to recreate the issue on my system:
![image](https://user-images.githubusercontent.com/8075565/69021303-5d5e8f80-0985-11ea-8672-6b3c27b37166.png)
I suspect it may be down to your NVIDIA drivers using high CPU, this is out of my control and cannot be fixed, however you can decrease the severity of the issue by changing the update rate. 

Depending on your version, this can be improved by adding `-u 5` to the command line arguments (if your version is above or equal to [c1fcbb7](https://github.com/abc123me/Nvidia-Fancontrol/commit/c1fcbb766e694f14512d0b56b072570f666468f9)). Otherwise you can change line 110 in `main.py` to be `sleep(5)` instead of `sleep(1)`.

Also please mention what CPU you have and make sure you're not looking at instantaneous CPU usage instead of usage over time, the above was ran on a `i5-3320M CPU @ 2.60GHz`
